baseURL = 'https://shipit.peterhollmer.com/'
languageCode = 'en-us'
title = 'Ship It'
theme = "papermod"

[params]
  description = "Tech insights and solutions from a software professional"
  author = "Pete Hollmer"
  
  # Theme behavior
  defaultTheme = "auto"
  ShowShareButtons = false
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = false
  ShowRssButtonInSectionTermList = true
  UseHugoToc = true
  disableSpecial1stPost = false
  disableScrollToTop = false
  comments = false
  hidemeta = false
  hideSummary = false
  showtoc = true
  tocopen = false

  # Home Info Mode
  [params.homeInfoParams]
    Title = "Ship It 🚀"
    Content = """
    Welcome! I'm Pete, a software professional sharing insights on technology, development practices, and solutions to real-world problems.
    
    Here you'll find practical technical content, lessons learned, and ideas worth shipping.
    """

  # Profile mode disabled (using info card instead)
  [params.profileMode]
    enabled = false

  # Social icons
  [[params.socialIcons]]
    name = "linkedin"
    url = "https://linkedin.com/in/peterhollmer"

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/VerilyPete"

  [[params.socialIcons]]
    name = "email"
    url = "#contact-modal"

  # Contact form configuration
  # Override formspreeEndpoint in GitHub Actions with your actual endpoint
  formspreeEndpoint = "YOUR_FORMSPREE_ENDPOINT"

# Menu
[[menu.main]]
  name = "Posts"
  url = "/posts/"
  weight = 10

[[menu.main]]
  name = "Tags"
  url = "/tags/"
  weight = 20

[[menu.main]]
  name = "Contact"
  url = "/contact/"
  weight = 30

# Markup settings for TOC
[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2
